cxx_compiler:                 # [win]
  - vs2019                    # [win]
c_compiler_version:           # [win]
  - 19                        # [win]
cxx_compiler_version:         # [win]
  - 19                        # [win]