{% set name = "networkit" %}
{% set version = "5.0.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "f59c48a7e7895c21635f8134205bcaba08ec3624207c8047ae07ca855f431b39" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{file_ext}}
    {{hash_type}}: {{hash_value}}
  
build:
  skip: True  # [py27 or py33 or win or win_64]
  number: 0
  script:
    - '{{PYTHON}} -m pip install --ignore-installed -vv .'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.5
    - ninja >=1.9.0
  host:
    - python
    - pip
    - setuptools
    - cython >=0.21
    - openmp
    - sphinx
    - sphinx_bootstrap_theme
    - wheel >=0.28
    - scikit-learn >=0.20.3
    - seaborn >=0.8.1
    - networkx
    - tabulate
    - matplotlib-base
    - ipython
    - jupyter_console
  run:
    - python
    - openmp
    - scikit-learn >=0.20.3
    - networkx
    - tabulate
    - pandas
    - matplotlib-base
    - seaborn >=0.8.1
    - ipython
    - jupyter_console
    
test:
  imports:
    - networkit

about:
  home: https://github.com/kit-parco/networkit
  license: MIT
  license_family: MIT
  license_file: License.txt
  summary: 'NetworKit is a growing open-source toolkit for large-scale network analysis.'
  description: |
           NetworKit is a growing open-source toolkit for large-scale network analysis. Its aim is to provide tools for the analysis of large networks in the size range from thousands to billions of edges. For this purpose, it implements efficient graph algorithms, many of them parallel to utilize multicore architectures. These are meant to compute standard measures of network analysis, such as degree sequences, clustering coefficients, and centrality measures. In this respect, NetworKit is comparable to packages such as NetworkX, albeit with a focus on parallelism and scalability. NetworKit is also a testbed for algorithm engineering and contains novel algorithms from recently published research (see list of Publications).
  doc_url: https://networkit.github.io/
  dev_url: https://github.com/kit-parco/networkit

extra:
  recipe-maintainers:
    - lucventurini  # Temporary, I am not involved with the development itself
    - angriman
    - fabratu
    - avdgrinten
