{% set name = "networkit" %}
{% set version = "9.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c574473bc7d86934f0f4b3049c0eeb9c4444cfa873e5fecda194ee5b1930f82c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: 'https://github.com/networkit/networkit/archive/{{ version }}.tar.gz'
    {{ hash_type }}: {{ hash_value }}
    patches:
      - 0001-Pass-conda-python-version.patch
  
build:
  skip: True  # [py27 or py33  or python_impl == 'pypy']
  skip: True  # [py<38 and win]
  number: 0
  script:
    - '{{ PYTHON }} -m pip install --install-option="build_ext" --install-option="--networkit-external-core" --install-option="--external-tlx={{ BUILD_PREFIX }}" --ignore-installed -vv .'
    - '{{ PYTHON }} -m pip install --install-option="build_ext" --install-option="--external-tlx={{ BUILD_PREFIX }}\Library" --ignore-installed -vv .'  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.5
    - cython >=0.29
    - ninja >=1.9.0
    - libtlx
    - libnetworkit ={{ version }}  # [not win]
    - python
  
  host:
    - numpy
    - pip
    - python
    - scipy
    - setuptools
    - setuptools-cythonize
    - wheel >=0.28
    - libnetworkit ={{ version }}  # [not win]

  run:
    - numpy
    - python
    - scipy
    - libnetworkit ={{ version }}  # [not win]

test:
  imports:
    - networkit

about:
  home: https://github.com/networkit/networkit
  license: MIT
  license_family: MIT
  license_file: License.txt
  summary: 'NetworKit is a growing open-source toolkit for large-scale network analysis.'
  description: |
           NetworKit is a growing open-source toolkit for large-scale network analysis. Its aim is to provide tools for the analysis of large networks in the size range from thousands to billions of edges. For this purpose, it implements efficient graph algorithms, many of them parallel to utilize multicore architectures. These are meant to compute standard measures of network analysis, such as degree sequences, clustering coefficients, and centrality measures. In this respect, NetworKit is comparable to packages such as NetworkX, albeit with a focus on parallelism and scalability. NetworKit is also a testbed for algorithm engineering and contains novel algorithms from recently published research (see list of Publications).
  doc_url: https://networkit.github.io/
  dev_url: https://github.com/networkit/networkit

extra:
  recipe-maintainers:
    - angriman
    - avdgrinten
    - fabratu
    - lucventurini  # Temporary, I am not involved with the development itself
