conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test_on_native_only: true

azure:
  settings_win:
      pool:
          vmImage: windows-2019
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: True
