travis:
  secure:
    BINSTAR_TOKEN: BptozEDOgCRzJMXJ5wU9y0N0buuBDMdmuEZ1BLL+GSP828LJS+5XlFWWVtnFjBPJmnru+z0sKxggvtTZl7iCuQ4iKNm5KmOp7wJNL1yLupreVMQrPw+E6h5yh0votsrWOVW4M55jCAk4Xaq/XDYA5vW+2MbqTxeE7pEJb6HhIRqWg+gDwNAASysox+rhlgBspg4P1W4QEOXkJVNMol/IV115Dkd7vIJ8GRkD2cNJOfOqTIVnQ+U4ydxjEGZDrlsU/73u8pUIKmp+m9PR9Fts0hWnPURE2YCSrqTP3x+OfS6AH7cGHhVunnXQa0PDyrrfTPqYIOSradRiNHRH01luxca3EqsS1F9Qj8tv32Gk1VJgYWja8OuWylx09Rh2huvOWXw4hP5zvKDOaLVucwMUDIM95pKrjrsdMC2yWHc99WsQPn9Zpr4dVwEAxCtZDtqlqIX+d7lyuuLN7munLWglXJV16zHIWFdUUi28hsb9fBKluv9/mn2pwvGKPq8wcOuN2MEcYpswPIc8E6YaB3891l+w9tY5TscJuoohKzBPGInyODCLHP9bKI+MYHQcs1p7e9x5J7ThXf2cVDZw0+E2FWundX0gUdgBLg0vj+2lHlE+tQyZB9euA6MsEyOAG7pzywtTjLNUIzYLtwB1upd0Nvu+JVz5qCW5H26jNZKsSNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
